### ISSUE TITLE
Render text from variable produce a comma

### ISSUE THREAD

**Issue by nsebhastian** [nodegui/react-nodegui#204] opened 2020-05-07 16:23 UTC
Rendering <Text> from a variable cause the renderer to print a `,` before the value.

Steps to reproduce:
The App code:

```
const App = () => {
  const myText = "MyText";

  return(
    <Window>
      <View>
        <Text>Source: {myText}</Text>
      </View>
    </Window>
  )
}
```

Result:
![2020-05-07 23_20_01-app jsx - react-nodegui-github - Visual Studio Code](https://user-images.githubusercontent.com/10413648/81319190-843a8a80-90b9-11ea-94f8-d78ee7aaeb31.png)

OS: Windows 10
package.json dependencies:
```
{
  "dependencies": {
    "@nodegui/nodegui": "^0.16.1",
    "@nodegui/react-nodegui": "^0.5.0",
    "axios": "^0.19.2",
    "open": "^7.0.3",
    "react": "^16.13.0"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/preset-env": "^7.8.7",
    "@babel/preset-react": "^7.8.3",
    "@babel/preset-typescript": "^7.8.3",
    "@nodegui/packer": "^1.4.0",
    "@types/node": "^13.9.3",
    "@types/react": "^16.9.23",
    "@types/webpack-env": "^1.15.1",
    "babel-loader": "^8.1.0",
    "clean-webpack-plugin": "^3.0.0",
    "file-loader": "^6.0.0",
    "fork-ts-checker-webpack-plugin": "^4.0.5",
    "native-addon-loader": "^2.0.1",
    "typescript": "^3.8.3",
    "webpack": "^4.42.0",
    "webpack-cli": "^3.3.11"
  }
}

```

**Comment by master-atul** [comment] 2020-05-07 17:18
Hi @nsebhastian 
A workaround for now could be:

```
const App = () => {
  const myText = "MyText";

  return(
    <Window>
      <View>
        <Text>{`Source: ${myText}`}</Text>
      </View>
    </Window>
  )
}
```

I think the issue is we are converting an array of values ["Source", myText] directly internally.

**Comment by shubhamzanwar** [comment] 2020-05-24 12:33
@nsebhastian Looks like you're using an older version of react-nodegui(0.5.0). This issue was fixed in one of the later versions. could you try upgrading to the latest version  (0.6.1) ?

That should solve it for you 🙂

**Closed** 2020-06-09 19:43 UTC
